CREATE TABLE pacientes (
  id BIGINT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL,
  telefone VARCHAR(16) NOT NULL,
  cpf CHAR(11) NOT NULL,
  logradouro VARCHAR(100) NOT NULL,
  bairro VARCHAR(100) NOT NULL,
  cep VARCHAR(9) NOT NULL,
  complemento VARCHAR(100),
  numero VARCHAR(100),
  uf CHAR(2) NOT NULL,
  cidade VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);
